djangoapp/urls.py
from django.urls import path
from . import views

app_name = 'djangoapp'

urlpatterns = [
    path('', views.index, name="index"),
    path('pref_quiz/', views.pref_quiz, name="pref_quiz"),
    path('pref_result/', views.pref_result, name="pref_result"),
    path('random_quiz/', views.random_quiz, name="random_quiz"),
    path('quiz_result/', views.quiz_result, name="quiz_result"),
    path('wiki/', views.wiki, name="wiki"),
    path('wiki_result/', views.wiki_result, name="wiki_result"),
]

djangostudy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
    path('', RedirectView.as_view(url='djangoapp/')),
]

djangoapp/models.py
from django.db import models

# Create your models here.

djangoapp/views.py
from django.shortcuts import render, redirect
from .quiz import *
# Create your views here.
def index(request):
    # template = 'index.html'
    context = {
        'title': 'QuizApp'
    }
    return render(request, 'index.html', context)

def pref_quiz(request):
    prefecture, city, url = prefecture_quiz()
    context = {
        'title': '県庁所在地クイズ',
        'prefecture': prefecture,
        'city': city,
        'url': url,
    }
    return render(request, 'prefecture_tpl.html', context)

def pref_result(request):
    if request.method == "POST":
        userinput_city = request.POST.get('userinput_city')
        prefecture = request.POST.get('prefecture')
        city = request.POST.get('city')
        url = request.POST.get('url')

        if city == userinput_city:
            result = '正解'
        else:
            result = '不正解'

        context = {
            'title': '県庁所在地クイズ - 結果',
            'result': result,
            'prefecture': prefecture,
            'city': city,
            'url': url,
        }

        return render(request, 'prefecture_result.html', context)

def random_quiz(request):
    selected_qa = quiz()

    num = [i for i in range(1, 6)]
    question = []
    answer = []
    for i in selected_qa:
        question.append(i[0])
        answer.append(i[1])
    context = {
        'title': 'ランダムクイズ',
        'num': num,
        'question': question,
        'answer': answer,
    }
    return render(request, 'quiz_tpl.html', context)

def quiz_result(request):
    if request.method == 'POST':
        score = 0
        user_answer = request.POST.getlist('user_answer')
        answer = request.POST.getlist('answer')
        for i, j in zip(user_answer, answer):
            if i == j:
                score += 20
        
        context = {
            'title': 'クイズの結果です',
            'score': score,
            'answer': answer,
            'user_answer': user_answer
        }
        return render(request, 'quiz_result.html', context)

def wiki(request):
    context = {
        'title': 'Python版Wikipediaで調べる',
    }
    return render(request, 'wiki_tpl.html', context)

def wiki_result(request):
    if request.method == 'GET':
        word = request.GET.get('word')
        result = wikipy(word)
        context = {
            'title': 'Python版wikipediaで調べる',
            'result': result,
        }
        return render(request, 'wiki_result.html', context)

templates/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>TOP</title>
    <style>body {margin: 30px; padding: 30px;}</style>
</head>
<body>
    <h1> {{ title }}</h1>
    <a href="{% url 'djangoapp:pref_quiz' %}">県庁所在地クイズ</a>
    <p></p>
    <a href="{% url 'djangoapp:random_quiz' %}">ランダムクイズ</a>
    <p></p>
    <a href="{% url 'djangoapp:wiki' %}">wikipediaで調べる</a>
</body>
</html>

templates/prefecture_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>    
</head>
<body>
    <h1>{{ title }}</h1>
    <p>結果は...<strong>{{ result }}</strong>でした！</p>
    <ul>
        <li>
            <p>{{ prefecture }}の県庁所在地は<strong>{{ city }}</strong>です。</p>
        </li>
        <li>
            <p>
                {{ prefecture }}のHPは
                <a href="{{ url }}" target="_blank" rel="noopener noreferrer">こちら</a>
            </p>
        </li>
    </ul>
    <a href="/">最初に戻る</a>
</body>
</html>

templates/prefecture_tpl.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ title }}</h1>
    <p><strong>{{ prefecture }}</strong>の県庁所在地は？</p>
    <form action="{% url 'djangoapp:pref_result' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="userinput_city" size="15">
        <input type="submit" value="送信">
        <input type="hidden" name="prefecture" value="{{ prefecture }}">
        <input type="hidden" name="city" value="{{ city }}">
        <input type="hidden" name="url" value="{{ url }}">
    </form>
    <p></p>
    <a href="/">最初へ戻る</a>
</body>
</html>

templates/quiz_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ title }}</h1>
    <p>結果は... <strong>{{ score }}</strong>点でした </p>
    {% load boost %}
    {% for i, j in answer|zip:user_answer %}
        <p>答え：{{ i }} | あなたの答え： {{ j }}</p>
    {% endfor %}
    <p></p>
    <a href="/">最初へ戻る</a>
</body>
</html>

templates/quiz_tpl.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ title }}</h1>
    <p>問題に挑戦してみよう</p>
    <form action="{% url 'djangoapp:quiz_result' %}" method="POST">
        {% csrf_token %}
        {% load boost %}
        {% for i, j in num|zip:question %}
            <p>問題{{ i }}:{{ j }}</p>
            <input type="text" name="user_answer" size="10">            
        {% endfor %}
        {% for k in answer %}
            <input type="hidden" name="answer" value="{{ k }}">
        {% endfor %}
        <input type="submit" value="送信">
    </form>
    <p></p>
    <a href="/">最初へ戻る</a>
</body>
</html>

templates/wiki_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ title }}</h1>
    {{ result }}
    <p></p>
    <a href="/">最初へ戻る</a>
</body>
</html>

templates/wiki_tpl.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ title }}</h1>
    <p>調べたいワードを入力してください</p>
    <form action="{% url 'djangoapp:wiki_result' %}" method="GET">
        <input type="text" name="word" size="15">
        <input type="submit" value="送信">
    </form>
    <p>{{ result }}</p>
    <a href="/">最初に戻る</a>
    
</body>
</html>